# Generated by Django 5.1.7 on 2025-03-16 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='participants_id',
            field=models.ManyToManyField(related_name='Participant_Groupe_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
