# Generated by Django 3.2.25 on 2025-03-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la classe')),
                ('description', models.TextField(verbose_name='Description de la classe')),
                ('image', models.ImageField(upload_to='images/cours/', verbose_name='Image de la classe')),
                ('nombreEtudiant', models.IntegerField(verbose_name="Nombre d'étudiants")),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentatives', models.IntegerField(verbose_name='Nombre de tentatives')),
                ('durée', models.DurationField(verbose_name="Durée de l'évaluation")),
                ('datecreation', models.DateField(verbose_name='Date de création')),
                ('heurecomposition', models.DateTimeField(verbose_name='Heure de composition')),
                ('datelimite', models.DateTimeField(verbose_name='Date limite')),
                ('jourComposition', models.CharField(max_length=100, verbose_name='Jour de la composition')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=255, verbose_name="Nom du type d'évaluation")),
                ('total', models.IntegerField(verbose_name='Total des points')),
            ],
            options={
                'verbose_name': "Type d'évaluation",
                'verbose_name_plural': "Types d'évaluation",
            },
        ),
    ]
