# Generated by Django 5.1.7 on 2025-03-10 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comptabilite', '0001_initial'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='operateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operateur_compte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='comptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptable_Paiement', to='account.comptable'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compte_Paiement', to='Comptabilite.compte'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_Paiement', to='Comptabilite.facture'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nature_Paiement', to='Comptabilite.nature'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='rapportFinancier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapportFinancier_Paiement', to='Comptabilite.rapportfinancier'),
        ),
    ]
